### ISSUE TITLE
Build a Framework for Authoring Lambda Handlers

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/panda-sky#11]
Currently when writing handlers, you are required to know a bit about how Lambdas are written and how to get at context variables.   It would be nice if there were an extra layer that extracted that context information and presented it more like Node servers:

```coffee
(request, response) ->
  # Magic with request
  response.write magic 
```

We might want to explore some of the popular conventions from Express (borrowing shamelessly from their docs):
```coffee
sky = do require 'panda-sky'

sky.get '/', (req, res) ->
  {name} = req
  res.send "hello #{name}"
```

And then we handle Lambda naming systematically.  Having a module that gets invoked would make it easier for developers to bridge the divide between what they wish to express and what AWS needs to deploy.

**Comment by dyoder** [comment]
I think we can layer this in, alongside the caching helpers. That is, I'm not sure we really need a framework.

I also don't like the Express-style handlers. First, they sort of work against the goal of having a first-class API definition. I think we can make a nod to that with helpers for building a definition, like we did with PBX. But having the handlers inline tends to clutter things up and make it difficult to see the API at a glance.

Really what we have is two helpers. One for caching and one for wrapping the interface to the lambda function as a function taking a request and a response.

We can have builder helpers, but that's a separate concern.

**Comment by dyoder** [comment]
Closing in favor of #22, #29, and #30.
