### ISSUE TITLE
Make Schema Validation Errors Less Cryptic

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/panda-sky#18]
It's not clear if this should be a Panda Sky ticket for a `jsck` ticket.  Schema validation errors are accurate, but cryptic for anyone unfamiliar with what it is trying to communicate.  They should be more human friendly.  We should map errors for `sky.yaml` and API description to more semantic errors in a system that know more about what is being described and how to address fixes.

**Comment by automatthew** [comment]
JSCK now has more helpful errors.
