### ISSUE TITLE
Establish HTTP Status Code Class and Apply Expected Codes Automatically

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/panda-sky#21]
This is related to thinking about #11.  The response handle could come with the ability to specify HTTP status codes manually, but there are some that we should support automatically.  And all of these potential codes need to be supported in the Gateway integration section.

For example:
If an endpoint is specified in the API description, but there is no lambda for it, Sky's framework should create a dummy lambda with the appropriate name that just returns a `501 Not Implemented`

**Comment by dyoder** [comment]
This is now tied to #29, not #11.
