### ISSUE TITLE
Establish an Beginner Friendly Roadmap

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/panda-sky#26]
@dyoder, I'm assigning this to you since you're writing the more narrative introductions, but I will offer my two cents. As I was writing this I found myself grouping these tasks into two, relatively orthogonal piles: a "structural feature" track and "stability" or "nice to have" track.  I'm not sure how someone with your experience would order their development.  

### Short Term
I think we need to start with the Panda Sky development framework (#11).  Not only is it the biggest technical risk, I think it's our biggest value-added to the AWS stack because it provides a uniform interface for the most customizable part of the deployment.  It's ***the foundation*** for future features, a foundation that is needed before adding more mixins.

I'd start with just a way to provide `request` and `response` objects that
1. bundle input parameters and 
2. allow status codes to propagate to the Gateway.   Then we can 
3. introduce a `$mixin` global that allows configuration to make it into the lambda's context.

I think think that's the bare minimum for both 
a. fixing the pain points with using the S3 mixin and 
b. adding new mixins with ease.

### Middle Term
- Start adding mixins.  As we've discussed, we can prioritize depending on our interests and the community's:
  - `s3`
  - `elasticache`
  - `rds`
  - `sns`
  - `sqs`
  -  (`ses` is not available in CloudFormation yet)
- Add Cognito integration.  This would be seperate from normal mixins 
- Improve caching implementation
- Address API logging
- Client (or is this longer term?)

### Long Term
- Database adapter/companion module
- Expand support for Python and Java.

### Short Term
- Adding the `sky build` command
- Schematize the environment and API descriptions

### Middle Term
- Interviewer for API and mixins
- Add the abilty to register domains and certs with Route53 and ACM
- Add semantic clarity to the configuration validation errors
- Git hook integration

### Long Term
- ???

**Comment by dyoder** [comment]
I'm not really sure what you're driving at here. Is this just input for prioritizing the tickets?

> Not only is it the biggest technical risk, I think it's our biggest value-added to the AWS stack because it provides a uniform interface for the most customizable part of the deployment.

I don't think there is much technical risk there at all. See #22, #29, and #30. I also think the greater value-add is what we've already done, which is to make it incredibly easy to publish APIs. There's lots more we can do, for sure, but I feel like you're focusing too much on that for some reason. But maybe I'm missing what you're getting at here?

> fixing the pain points with using the S3 mixin

What are you referring to here? Is this ticketed?

> introduce a $mixin global that allows configuration to make it into the lambda's context

We have a more general problem, which is providing context beyond the request and response. In #22, I refer to getting the caching policy from the API definition. The context could include the API definition and other things, like the mixins.

We could provide some simple helper functions or just have the wrapper in #29 just read those into the context. But this is straightforward either way.

**Comment by freeformflow** [comment]
Panda Sky as it exists proves that we can quickly publish a functional API to cloud infrastructure.  But without helpers, it's kinda annoying to actually construct the code you'd like to publish.  Getting the form to be appealing is going to be key to Panda Sky being chosen over people that snap together AWS technology.

The S3 pain point is ticketed in #13. 

I can get behind stuffing all the external config into one object so it can be injected into the Lambda's context.

**Comment by freeformflow** [comment]
I laid it out like this because I ended up with two piles of tickets.  There's a pile of blocking, feature building tickets that are exciting and give Panda Sky more super powers.   And then there's a pile of tickets aren't really blocking.  While they relieve pain points, they are sorta good citizen vegetable tickets, haha.

I know both piles are important, and I wanted to rely on you to guide the balance of what would be best for Panda Sky adoption.

**Comment by dyoder** [comment]
> …being chosen over people that snap together AWS technology

What are referring to here? I think this may be part of the confusion.

> There's a pile of blocking, feature building tickets…

What do you mean blocking?

**Comment by dyoder** [comment]
I've added/updated milestones. Feedback welcome. I sort of ignored this because I'm still not sure I understand it, so maybe it makes sense to talk about specific tickets and where they belong, that is, if you feel they're misplaced.

**Comment by dyoder** [comment]
One question I have is: how are we handling the S3 mixin now? Is just built in for the moment?

**Comment by dyoder** [comment]
Closing. See #32, #33.
