### ISSUE TITLE
Helper for request, response signature

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-sky#29]
The Lambda interface is not an HTTP interface, since the Lambda can be called in a variety of ways. For our purposes, we'd like to present a simple `(request, response)` style interface for implementing handlers. This can be done by writing a second order function, ex: `lambda` that adapts such a function for use as a Lambda function.

This helper could be used in conjunction with the caching helper, ex:

``` coffee
{lambda, cache} = require "http-server-helpers"
Greeting.create = lambda cache (context) ->
  context.response.write "Hello!"
```

**Comment by automatthew** [comment]
Resolved by my work with the Request Mapping Template.
