### ISSUE TITLE
Add "sky mixin" command

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-sky#31]

**Comment by dyoder** [comment]
Initial version need only support `add s3`

**Comment by dyoder** [comment]
Mixins currently consist of:

- schema for configuration
- configuration
- Handlebars template for CF

**Comment by freeformflow** [comment]
Don't forget the fourth component: "pre-processor" code that modifies the configuration at runtime.

For example: In the S3 mixin, the pre-processor runs a check for the existence of the desired bucket.  
1. If the bucket does ***not*** exist, the preprocessor adds the bucket configuration to the CFo stack description
2. If the bucket ***does exist***, the preprocessor omits the bucket configuration and the stack will just point to the existing bucket and whatever data is currently contains.
