### ISSUE TITLE
Require `panda-sky` not individual modules

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-sky#39]
Currently we ask the developer to install Fairmont and JS-YAML. I'd prefer we had a way to simply require `panda-sky` instead. And then have `sky init` ask whether it's okay to update the `package.json`.

**Comment by dyoder** [comment]
It kind of kills the coolness of the quick start that you have to stop and `npm install` stuff.

**Comment by freeformflow** [comment]
Okay.   I sorta thought about that, but then I imagined you talking about not doing unexpected or annoying things to users, haha.

But, if we ask for permission first, we stay kosher?

**Comment by dyoder** [comment]
Understandable hesitation. But yeah I think if we ask in the interviewer it's okay. Ex:

```
Add panda-sky as a dependency to package.json? [Y/n]
```
