### ISSUE TITLE
Sometimes sky publish hangs or crashes

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-sky#42]
https://asciinema.org/a/9rss8zy3ptlf6fljz61pwe5hm

**Comment by dyoder** [comment]
Note that the above terminal capture fast-forwards anything longer than 5 seconds. See the elapsed time, though:

`>>> elapsed time 9m1s`

**Comment by dyoder** [comment]
This time it didn't hang, but just crashed, flat out.

https://asciinema.org/a/acutp0rtt1v0wponuq7meiqvy

**Comment by freeformflow** [comment]
So far, I've had trouble reproducing this error.  I don't exactly want to close this bug, but I think it should be de-prioritized for the time being while I focus on the S3 mixin to make Blurb9 deployment stable.  From what I can tell, the hello-world no mixin configuration is currently stable.
