### ISSUE TITLE
Support 4XX / 5XX class errors to be triggered at will

### ISSUE THREAD

**Issue by maximbert** [pandastrike/panda-sky#53]
Currently, it seems impossible to trigger a 404 from Blurb (see issue https://github.com/pandastrike/blurb9/issues/118), yet this should be possible.

**Comment by freeformflow** [comment]
This is now supported by listing expected status codes in the `signature.status` field of the action description.  Requiring Panda Sky within a Lambda also gives the developer access to an HTTP response wrapped in a JS `Error`, which can be thrown at will.
