### ISSUE TITLE
Custom Lambda timeout (to get more than the default 3 seconds)

### ISSUE THREAD

**Issue by maximbert** [pandastrike/panda-sky#59]
When working on a blurb.update handler, which happens to have 2 slow calls to S3, I get`Task timed out after 3.00 seconds`. Sky should allow to bump the Lambda's timeout.

**Comment by maximbert** [comment]
The issue was not related to timeout setup per say, the handler was not being found, and the lambda would just wait until timing out. I have a fix for that within Blurb9 (i.e. error out if no handler), but I still believe a custom timeout feature would be valuable.

**Comment by automatthew** [comment]
1. I've increased the Lambda timeout to 15 seconds for all requests.

2. In future, we may specify timeouts for individual Resource Methods using the `pragma` directive in PSADv1
