### ISSUE TITLE
No Such File: `/panda-sky/init/s3.js`

### ISSUE THREAD

**Issue by cardoni** [pandastrike/panda-sky#61]
After installing globally, upon running `sky init` I'm seeing the following error:

```shell
Error: ENOENT: no such file or directory, open '/Users/greg/.nvm/versions/node/v6.10.2/lib/node_modules/panda-sky/init/s3.js'
    at Error (native)
```

![image](https://cloud.githubusercontent.com/assets/674107/25106687/b7f02d8a-237f-11e7-9d07-4440e6f364ad.png)

Looks like [`/src/init.coffee#L56`](https://github.com/pandastrike/panda-sky/blob/master/src/init.coffee#L56) is pointing to the wrong location for `s3.js`.

**Comment by cardoni** [comment]
Looks like this ticket is a dupe of #44

**Comment by dyoder** [comment]
We're updating a few things. Looks like the README is also out of date. cc @freeformflow

**Comment by freeformflow** [comment]
Okay, I've adjusted the `sky init` command and ReadMe to reflect some recent changes.  The quickstart should work for you now.  I should warn you that within the next week we are going to upgrade how we represent API descriptions to enforce stricter content types and to better support header parsing.  I will update the ReadMe when that change is finalized.

Please pull `beta-08` with `npm install panda-sky -g` and try agin.

**Comment by freeformflow** [comment]
To clarify, simply run `npm install panda-sky -g` to ***install*** the version of Panda Sky that I published this evening, `beta-08`

**Comment by cardoni** [comment]
Works perfectly now.  Thanks, @freeformflow!
