### ISSUE TITLE
Terminology In API Definition

### ISSUE THREAD

**Issue by dyoder** [pandastrike/panda-sky#68]
The reason i favored _method_ in the API definition (versus action or handler) is because it maps precisely to the web itself. Resources have representations and methods. So if we're declaring a thing called _resources_, it follows we would declare a thing called _methods_ that a given resource supports. Since part of the Panda Way wrt to HTTP is to get out of the way, we want isomorphic terminology. I don't see any conflation or conflict in using _method_ to refer to the, uh, method.

The _name_ of the method is _not_ the method. a _method_ of a resource must have a _name_, but we can insist that the method is more than a simple attribute of the request, since that is not part of HTTP, but merely an artifact of frameworks encapsulating a request.

The next level down in the hierarchy are, in fact, headers and are thus not conceptually bound in the same manner. Thus, the idea of a _method_ having a _signature_. The signature is tacitly defined by the headers. but there is no HTTP concept that maps directly to it, so we can't borrow from HTTP directly in that case.

However, that concept _does_ readily map to the world of functions and since we are ultimately mapping from a request to function, it seems natural to introduce function-like semantics at that level. A _signature_ of a method can map directly to the signature of a function.

So it's within the definition of method that we cross the threshold, if you will, from the network into a process space…

What is obviously missing, however, is the notion of _representations_. I had considered simply making _representations_ orthogonal to _methods_. So we'd have a separate attribute at the same level, indicating which representations that resource supports. The signature could then represent them by name. However, i deferred that since a) I wasn't sure how to do it and b) I wanted to get Sky working.

The _method_ thing was easy, though, so I went with that.

This is _why_ i was doing that. Whether in practice it introduces confusion is another q. :)

**Comment by dyoder** [comment]
@automatthew said:

> I feel that we do not have enough parallax on using representations yet to make quality decisions.

I responded:

> I think it's one of these things where we just Trust In Roy and things work out. But until we try it…

**Comment by automatthew** [comment]
PSADv1 uses the "method" terminology.
