### ISSUE TITLE
Formalize Integration Response Templates

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/panda-sky#72]
For a given content-type of a HTML response, we need a way to instruct Gateway to map data from the compute layer into an HTTP response.  Specifically, we need a way to add Integration Response mapping templates (in the Velocity DSL).

We currently have a hard-coded a solution for `text/html`.  We need to generalize and formalize this, please.

**Comment by automatthew** [comment]
> We currently have a hard-coded a solution for text/html

Where is this; having trouble locating it.

**Comment by automatthew** [comment]
Just dropping links to relevant docs.

https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html

**Comment by freeformflow** [comment]
This PR has the relevant changes.  I worked with Max and Jesse yesterday to get it coded and merged so they would be unblocked.  https://github.com/pandastrike/panda-sky/pull/71/files

**Comment by automatthew** [comment]
We've decided on a different approach to that particular problem of supplying HTML.
